//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Client.cat_local
{
    using System;
    using System.Collections.Generic;
    
    public partial class info
    {
        public int Id { get; set; }
        public string platform { get; set; }
        public string os { get; set; }
        public string image { get; set; }
        public string bios { get; set; }
        public string wlan_hwid { get; set; }
        public string wlan_driver { get; set; }
        public string lan_hwid { get; set; }
        public string lan_driver { get; set; }
        public string nfc_hwid { get; set; }
        public string nfc_driver { get; set; }
        public string rfid_hwid { get; set; }
        public string rfid_driver { get; set; }
        public string bt_hwid { get; set; }
        public string bt_driver { get; set; }
        public string wwan_hwid { get; set; }
        public string wwan_ude { get; set; }
        public string wwan_gnss { get; set; }
        public string wwan_firmware { get; set; }
        public string wwan_driver { get; set; }
        public Nullable<System.DateTime> change { get; set; }
    }
}
