//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Client.cat_local
{
    using System;
    using System.Collections.Generic;
    
    public partial class info
    {
        public int Id { get; set; }
        public string platform { get; set; }
        public string os { get; set; }
        public string image { get; set; }
        public string bios { get; set; }
        public string wlan_hwid { get; set; }
        public string wlan_driver { get; set; }
        public string lan_hwid { get; set; }
        public string lan_driver { get; set; }
        public string nfc_hwid { get; set; }
        public string nfc_driver { get; set; }
        public string rfid_hwid { get; set; }
        public string rfid_driver { get; set; }
        public string bt_hwid { get; set; }
        public string bt_driver { get; set; }
        public string wwan_hwid { get; set; }
        public string wwan_ude { get; set; }
        public string wwan_gnss { get; set; }
        public string wwan_firmware { get; set; }
        public string wwan_driver { get; set; }
        public Nullable<System.DateTime> change { get; set; }
    }
}
