//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Client.cat_local
{
    using System;
    using System.Collections.Generic;
    
    public partial class pwr
    {
        public int Id { get; set; }
        public string action { get; set; }
        public int state { get; set; }
        public int task_id { get; set; }
        public string task { get; set; }
        public System.DateTime time { get; set; }
    }
}
