//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Client.cat_local
{
    using System;
    using System.Collections.Generic;
    
    public partial class task
    {
        public int local_id { get; set; }
        public string task1 { get; set; }
        public string state { get; set; }
        public string result_loc { get; set; }
        public Nullable<System.DateTime> start { get; set; }
        public Nullable<System.DateTime> finish { get; set; }
        public string series { get; set; }
        public Nullable<int> server_id { get; set; }
        public string result_ids { get; set; }
        public string is_update { get; set; }
        public string ap { get; set; }
    }
}
