
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class AP
{

    public int No { get; set; }

    public string Type { get; set; }

    public string Platform { get; set; }

    public string Vender { get; set; }

    public string Select { get; set; }

    public Nullable<double> Cycles { get; set; }

    public string CPU { get; set; }

    public string WI1_chip1 { get; set; }

    public string WI1_protocols { get; set; }

    public string WI1_chip2 { get; set; }

    public string WI2_protocols { get; set; }

    public string Support_LTE { get; set; }

    public string C5G { get; set; }

    public string Network_technology_standard { get; set; }

    public string Adapter { get; set; }

    public string Location { get; set; }

    public string Status { get; set; }

    public string admin_ID { get; set; }

    public string admin_PW { get; set; }

    public string SSID { get; set; }

    public Nullable<double> PW { get; set; }

    public string SSID_5G { get; set; }

    public Nullable<double> PW1 { get; set; }

    public string C2_4G_BSSID { get; set; }

    public string C2_4G_Band { get; set; }

    public string C5G_BSSID { get; set; }

    public Nullable<double> C5G_Band { get; set; }

    public string FW_Version { get; set; }

    public string Remark { get; set; }

    public string F30 { get; set; }

    public bool active { get; set; }

}

}
