
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class auth_user_groups
{

    public int id { get; set; }

    public int user_id { get; set; }

    public int group_id { get; set; }



    public virtual auth_group auth_group { get; set; }

    public virtual auth_user auth_user { get; set; }

}

}
