
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class auth_user
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public auth_user()
    {

        this.auth_user_groups = new HashSet<auth_user_groups>();

        this.auth_user_user_permissions = new HashSet<auth_user_user_permissions>();

        this.django_admin_log = new HashSet<django_admin_log>();

    }


    public int id { get; set; }

    public string password { get; set; }

    public Nullable<System.DateTime> last_login { get; set; }

    public bool is_superuser { get; set; }

    public string username { get; set; }

    public string first_name { get; set; }

    public string last_name { get; set; }

    public string email { get; set; }

    public bool is_staff { get; set; }

    public bool is_active { get; set; }

    public System.DateTime date_joined { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<auth_user_groups> auth_user_groups { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<auth_user_user_permissions> auth_user_user_permissions { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<django_admin_log> django_admin_log { get; set; }

}

}
