
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class CAT_info
{

    public string Platform { get; set; }

    public string SN { get; set; }

    public string STATUS { get; set; }

    public string CurrentTask { get; set; }

    public string OS { get; set; }

    public string Image { get; set; }

    public string BIOS { get; set; }

    public string WLAN_Module { get; set; }

    public string WLAN_Driver { get; set; }

    public string BT_Module { get; set; }

    public string BT_Driver { get; set; }

    public string WWAN_Module { get; set; }

    public string WWAN_Driver { get; set; }

    public string GNSS_Module { get; set; }

    public string GNSS_Driver { get; set; }

    public string NIC_Module { get; set; }

    public string NIC_Driver { get; set; }

    public string NFC_Module { get; set; }

    public string NFC_Driver { get; set; }

    public string RFID_Module { get; set; }

    public string RFID_Driver { get; set; }

    public Nullable<System.DateTime> LastUsedTime { get; set; }

    public string Tag { get; set; }

    public string WWAN_Firmware { get; set; }

    public string WWAN_Modem { get; set; }

    public string AP { get; set; }

}

}
