//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Client.cat_server
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAT_info
    {
        public string Platform { get; set; }
        public string SN { get; set; }
        public string STATUS { get; set; }
        public string CurrentTask { get; set; }
        public string OS { get; set; }
        public string Image { get; set; }
        public string BIOS { get; set; }
        public string WLAN_Module { get; set; }
        public string WLAN_Driver { get; set; }
        public string BT_Module { get; set; }
        public string BT_Driver { get; set; }
        public string WWAN_Module { get; set; }
        public string WWAN_Driver { get; set; }
        public string GNSS_Module { get; set; }
        public string GNSS_Driver { get; set; }
        public string NIC_Module { get; set; }
        public string NIC_Driver { get; set; }
        public string NFC_Module { get; set; }
        public string NFC_Driver { get; set; }
        public string RFID_Module { get; set; }
        public string RFID_Driver { get; set; }
        public Nullable<System.DateTime> LastUsedTime { get; set; }
        public string Tag { get; set; }
        public string WWAN_Firmware { get; set; }
        public string WWAN_Modem { get; set; }
    }
}
