
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class DriverTable
{

    public int ID { get; set; }

    public string Prouct { get; set; }

    public string SW_Manager { get; set; }

    public string Modules { get; set; }

    public string Device { get; set; }

    public string OS { get; set; }

    public string Deliverables { get; set; }

    public string Version { get; set; }

}

}
