//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Client.cat_server
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverTable
    {
        public int ID { get; set; }
        public string Prouct { get; set; }
        public string SW_Manager { get; set; }
        public string Modules { get; set; }
        public string Device { get; set; }
        public string OS { get; set; }
        public string Deliverables { get; set; }
        public string Version { get; set; }
    }
}
