
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class ERDTable
{

    public long ID { get; set; }

    public string Deliverables_Name { get; set; }

    public string Short_Name { get; set; }

    public string Owner { get; set; }

    public string Vender_ID { get; set; }

    public string Device_ID { get; set; }

    public string Subsys_Vender_ID { get; set; }

    public string Subsys_Device_ID { get; set; }

}

}
