//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Client.cat_server
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class lab_server : DbContext
    {
        public lab_server()
            : base("name=lab_server")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CAT_info> CAT_info { get; set; }
        public virtual DbSet<DriverTable> DriverTable { get; set; }
        public virtual DbSet<ERDTable> ERDTable { get; set; }
        public virtual DbSet<IUR_mail_list> IUR_mail_list { get; set; }
        public virtual DbSet<LogListTable> LogListTable { get; set; }
        public virtual DbSet<ODM_functional_test> ODM_functional_test { get; set; }
        public virtual DbSet<ODM_stress_test> ODM_stress_test { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<task_result_analysis> task_result_analysis { get; set; }
        public virtual DbSet<taskTable> taskTable { get; set; }
        public virtual DbSet<test_report_table> test_report_table { get; set; }
        public virtual DbSet<TestLogTable> TestLogTable { get; set; }
        public virtual DbSet<UnitTable> UnitTable { get; set; }
        public virtual DbSet<UnitTable_test> UnitTable_test { get; set; }
        public virtual DbSet<UnknowLogTable> UnknowLogTable { get; set; }
    }
}
