

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class lab_server : DbContext
{
    public lab_server()
        : base("name=lab_server")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<CAT_info> CAT_info { get; set; }

    public virtual DbSet<DriverTable> DriverTable { get; set; }

    public virtual DbSet<ERDTable> ERDTable { get; set; }

    public virtual DbSet<IUR_mail_list> IUR_mail_list { get; set; }

    public virtual DbSet<LogListTable> LogListTable { get; set; }

    public virtual DbSet<ODM_functional_test> ODM_functional_test { get; set; }

    public virtual DbSet<ODM_stress_test> ODM_stress_test { get; set; }

    public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }

    public virtual DbSet<task_result_analysis> task_result_analysis { get; set; }

    public virtual DbSet<taskTable> taskTable { get; set; }

    public virtual DbSet<test_report_table> test_report_table { get; set; }

    public virtual DbSet<TestLogTable> TestLogTable { get; set; }

    public virtual DbSet<UnitTable> UnitTable { get; set; }

    public virtual DbSet<UnitTable_test> UnitTable_test { get; set; }

    public virtual DbSet<UnknowLogTable> UnknowLogTable { get; set; }

    public virtual DbSet<auth_group> auth_group { get; set; }

    public virtual DbSet<auth_group_permissions> auth_group_permissions { get; set; }

    public virtual DbSet<auth_permission> auth_permission { get; set; }

    public virtual DbSet<auth_user> auth_user { get; set; }

    public virtual DbSet<auth_user_groups> auth_user_groups { get; set; }

    public virtual DbSet<auth_user_user_permissions> auth_user_user_permissions { get; set; }

    public virtual DbSet<django_admin_log> django_admin_log { get; set; }

    public virtual DbSet<django_content_type> django_content_type { get; set; }

    public virtual DbSet<django_migrations> django_migrations { get; set; }

    public virtual DbSet<django_session> django_session { get; set; }

    public virtual DbSet<test_scripts> test_scripts { get; set; }

    public virtual DbSet<AP> AP { get; set; }

}

}

