
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class LogListTable
{

    public long ID { get; set; }

    public Nullable<System.DateTime> Update_Time { get; set; }

    public string Source { get; set; }

    public string Detail { get; set; }

    public bool whitelist { get; set; }

    public bool blacklist { get; set; }

    public Nullable<bool> IsEventLogDetail { get; set; }

    public Nullable<bool> IsWWAN { get; set; }

    public Nullable<bool> IsWLAN { get; set; }

    public Nullable<bool> IsNIC { get; set; }

    public Nullable<bool> IsNFC { get; set; }

    public Nullable<bool> IsBT { get; set; }

    public Nullable<bool> IsGNSS { get; set; }

}

}
