
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class ODM_stress_test
{

    public int ID { get; set; }

    public string platform { get; set; }

    public string OS { get; set; }

    public string BIOS { get; set; }

    public string module { get; set; }

    public string driver_version { get; set; }

    public string firmware_version { get; set; }

    public string test_script { get; set; }

    public string note { get; set; }

    public Nullable<System.DateTime> start_day { get; set; }

    public Nullable<System.DateTime> end_day { get; set; }

}

}
