//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Client.cat_server
{
    using System;
    using System.Collections.Generic;
    
    public partial class ODM_stress_test
    {
        public int ID { get; set; }
        public string platform { get; set; }
        public string OS { get; set; }
        public string BIOS { get; set; }
        public string module { get; set; }
        public string driver_version { get; set; }
        public string firmware_version { get; set; }
        public string test_script { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> start_day { get; set; }
        public Nullable<System.DateTime> end_day { get; set; }
    }
}
