
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class taskTable
{

    public int ID { get; set; }

    public string SN { get; set; }

    public string task { get; set; }

    public string state { get; set; }

    public string result { get; set; }

    public Nullable<System.DateTime> startTime { get; set; }

    public Nullable<System.DateTime> finishTime { get; set; }

    public string series { get; set; }

    public Nullable<int> local_id { get; set; }

    public string result_id { get; set; }

    public string ap { get; set; }

}

}
