
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class test_report_table
{

    public int ID { get; set; }

    public int reportID { get; set; }

    public int taskID { get; set; }

    public string owner { get; set; }

    public bool needSendMail { get; set; }

}

}
