
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class TestLogTable
{

    public long ID { get; set; }

    public System.DateTime Update_Time { get; set; }

    public Nullable<long> TaskID { get; set; }

    public string LocalID { get; set; }

    public string SN { get; set; }

    public Nullable<long> LogListID { get; set; }

    public string Source { get; set; }

    public string EventName { get; set; }

    public int LogLevel { get; set; }

    public string LogLevelDisplayName { get; set; }

    public Nullable<System.DateTime> TimeCreated { get; set; }

    public Nullable<int> LogID { get; set; }

    public Nullable<int> Task { get; set; }

    public Nullable<int> ProcessID { get; set; }

    public string ProviderName { get; set; }

    public Nullable<long> Count { get; set; }

    public string Detail { get; set; }

    public string BIOS { get; set; }

    public string OS { get; set; }

    public string WWAN_Name { get; set; }

    public string WWAN_Driver { get; set; }

    public string WWAN_FW { get; set; }

    public string GNSS_Driver { get; set; }

    public string WLAN_Name { get; set; }

    public string WLAN_Driver { get; set; }

    public string BT_Name { get; set; }

    public string BT_Driver { get; set; }

    public string NIC_Name { get; set; }

    public string NIC_Driver { get; set; }

    public string NFC_Name { get; set; }

    public string NFC_Driver { get; set; }

}

}
