
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class test_scripts
{

    public string name { get; set; }

    public string path { get; set; }

    public string tool { get; set; }

    public Nullable<bool> wwan { get; set; }

    public Nullable<bool> wlan { get; set; }

    public Nullable<bool> lan { get; set; }

    public Nullable<bool> bt { get; set; }

    public Nullable<bool> nic { get; set; }

    public Nullable<bool> rfid { get; set; }

}

}
