//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cat_Client.cat_server
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitTable
    {
        public string SN { get; set; }
        public string platformName { get; set; }
        public string phase { get; set; }
        public string SKU { get; set; }
        public string CAT { get; set; }
        public string borrower { get; set; }
        public string unitStatus { get; set; }
        public string yearCycle { get; set; }
        public string category { get; set; }
        public string note { get; set; }
        public Nullable<System.DateTime> borrowingDate1 { get; set; }
        public string position { get; set; }
        public System.DateTime keyInTime { get; set; }
        public string mailOne { get; set; }
        public string mailTwo { get; set; }
        public string mailThree { get; set; }
        public Nullable<System.DateTime> borrowingDate2 { get; set; }
        public Nullable<System.DateTime> borrowingDate3 { get; set; }
        public string CPU { get; set; }
        public string WLAN { get; set; }
        public string noteOne { get; set; }
        public string noteTwo { get; set; }
        public string noteThree { get; set; }
        public int ID { get; set; }
    }
}
