
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Cat_Client.cat_server
{

using System;
    using System.Collections.Generic;
    
public partial class UnitTable_test
{

    public string SN { get; set; }

    public string platformName { get; set; }

    public string phase { get; set; }

    public string SKU { get; set; }

    public string CAT { get; set; }

    public string borrower { get; set; }

    public string unitStatus { get; set; }

    public string yearCycle { get; set; }

    public string category { get; set; }

    public string note { get; set; }

    public Nullable<System.DateTime> borrowingDate1 { get; set; }

    public string position { get; set; }

    public Nullable<System.DateTime> keyInTime { get; set; }

    public string mailOne { get; set; }

    public string mailTwo { get; set; }

    public string mailThree { get; set; }

    public Nullable<System.DateTime> borrowingDate2 { get; set; }

    public Nullable<System.DateTime> borrowingDate3 { get; set; }

    public string CPU { get; set; }

    public string WLAN { get; set; }

    public string noteOne { get; set; }

    public string noteTwo { get; set; }

    public string noteThree { get; set; }

    public int ID { get; set; }

}

}
